spec:

  templates:

  - name: train-model
    parent: generic-task

    inputs:

      parameters:
      - name: docker-image
        value: z-ml
      - name: docker-tag
        value: latest

      - name: command
        value: python3 main.py

      artifacts:
      - name: main-script
        path: /app/main.py
        raw:
          data: |
            import json
            from simple.utils import save_json 
            from simple.functions import train_model

            predictions = train_model()
            result = {}
            result["predictions"] = predictions
            save_json(result, 'result.json')
  
    outputs:
      artifacts:
      - name: result
        path: /app/result.json
