spec:

  templates:

  - name: train-model
    parent: generic-task

    inputs:

      parameters:
      - name: docker-image
        value: z-ml
      - name: docker-tag
        value: latest

      - name: hidden_layer
      - name: epochs
      - name: lr

      - name: command
        value: python3 main.py

      artifacts:
      - name: main-script
        path: /app/main.py
        raw:
          data: |
            from sklearn.utils import save_json 
            from sklearn.functions import train_model

            model_name = {{inputs.parameters.model_name}}

            predictions, score = train_model(model_name)
            result = {}
            result["predictions"] = predictions
            result["score"] = score
            save_json(result, 'result.json')
  
    outputs:
      artifacts:
      - name: result
        path: /app/result.json
